// Code generated by "stringer -type=ClassType"; DO NOT EDIT.

package resolver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClassTypeNone-0]
	_ = x[ClassTypeClass-1]
	_ = x[ClassTypeSubclass-2]
}

const _ClassType_name = "ClassTypeNoneClassTypeClassClassTypeSubclass"

var _ClassType_index = [...]uint8{0, 13, 27, 44}

func (i ClassType) String() string {
	if i < 0 || i >= ClassType(len(_ClassType_index)-1) {
		return "ClassType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClassType_name[_ClassType_index[i]:_ClassType_index[i+1]]
}
