// Code generated by "stringer -type=FunctionType"; DO NOT EDIT.

package resolver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FunctionTypeNone-0]
	_ = x[FunctionTypeFunction-1]
	_ = x[FunctionTypeInitializer-2]
	_ = x[FunctionTypeMethod-3]
}

const _FunctionType_name = "FunctionTypeNoneFunctionTypeFunctionFunctionTypeInitializerFunctionTypeMethod"

var _FunctionType_index = [...]uint8{0, 16, 36, 59, 77}

func (i FunctionType) String() string {
	if i < 0 || i >= FunctionType(len(_FunctionType_index)-1) {
		return "FunctionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FunctionType_name[_FunctionType_index[i]:_FunctionType_index[i+1]]
}
