// Code generated by `go run ../tool/genast.go`; DO NOT EDIT.

package parser

import "github.com/fosmjo/lox/scanner"

type Expr interface {
    Accept(ExprVisitor) interface{}
}

type ExprVisitor interface {
    VisitAssignExpr(AssignExpr) interface{}
    VisitBinaryExpr(BinaryExpr) interface{}
    VisitGroupingExpr(GroupingExpr) interface{}
    VisitLiteralExpr(LiteralExpr) interface{}
    VisitLogicalExpr(LogicalExpr) interface{}
    VisitUnaryExpr(UnaryExpr) interface{}
    VisitVariableExpr(VariableExpr) interface{}
}

type AssignExpr struct {
    Name scanner.Token
    Value Expr
}

func NewAssignExpr(name scanner.Token, value Expr) AssignExpr {
    return AssignExpr{
        Name: name,
        Value: value,
    }
}

func (expr AssignExpr) Accept(visitor ExprVisitor) interface{} {
    return visitor.VisitAssignExpr(expr)
}

type BinaryExpr struct {
    Left Expr
    Operator scanner.Token
    Right Expr
}

func NewBinaryExpr(left Expr, operator scanner.Token, right Expr) BinaryExpr {
    return BinaryExpr{
        Left: left,
        Operator: operator,
        Right: right,
    }
}

func (expr BinaryExpr) Accept(visitor ExprVisitor) interface{} {
    return visitor.VisitBinaryExpr(expr)
}

type GroupingExpr struct {
    Expression Expr
}

func NewGroupingExpr(expression Expr) GroupingExpr {
    return GroupingExpr{
        Expression: expression,
    }
}

func (expr GroupingExpr) Accept(visitor ExprVisitor) interface{} {
    return visitor.VisitGroupingExpr(expr)
}

type LiteralExpr struct {
    Value interface{}
}

func NewLiteralExpr(value interface{}) LiteralExpr {
    return LiteralExpr{
        Value: value,
    }
}

func (expr LiteralExpr) Accept(visitor ExprVisitor) interface{} {
    return visitor.VisitLiteralExpr(expr)
}

type LogicalExpr struct {
    Left Expr
    Operator scanner.Token
    Right Expr
}

func NewLogicalExpr(left Expr, operator scanner.Token, right Expr) LogicalExpr {
    return LogicalExpr{
        Left: left,
        Operator: operator,
        Right: right,
    }
}

func (expr LogicalExpr) Accept(visitor ExprVisitor) interface{} {
    return visitor.VisitLogicalExpr(expr)
}

type UnaryExpr struct {
    Operator scanner.Token
    Right Expr
}

func NewUnaryExpr(operator scanner.Token, right Expr) UnaryExpr {
    return UnaryExpr{
        Operator: operator,
        Right: right,
    }
}

func (expr UnaryExpr) Accept(visitor ExprVisitor) interface{} {
    return visitor.VisitUnaryExpr(expr)
}

type VariableExpr struct {
    Name scanner.Token
}

func NewVariableExpr(name scanner.Token) VariableExpr {
    return VariableExpr{
        Name: name,
    }
}

func (expr VariableExpr) Accept(visitor ExprVisitor) interface{} {
    return visitor.VisitVariableExpr(expr)
}

